# Generated by Django 4.2.25 on 2025-10-31 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmissionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'EmissionType',
                'verbose_name_plural': 'EmissionTypes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Emission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('emissions', models.FloatField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emissions', to='core.activity')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emissions', to='core.country')),
                ('emission_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emissions', to='core.emissiontype')),
            ],
            options={
                'verbose_name': 'Emission',
                'verbose_name_plural': 'Emissions',
                'ordering': ['-year', 'country', 'activity'],
            },
        ),
    ]
